### ISSUE TITLE
Show something if icon can not be found

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#95]
If I mistype the icon name, and I don't have an image, then it should show me something other than the ghost indicator. 

eg I type "standard:accoun" and miss the t on the end. 

Suggest showing a blank icon like standard:default

**Comment by JodieM** [comment]
@tschug just adding this one for you, because I know you were working on this, and it is a lovely idea.

**Comment by tschug** [comment]
I like the concept, but I do think it's too heavy of a lift to be able to verify the 2nd half.  We could do the `standard:` and `custom:` stuff, but I'm skeptical of being able to "spell check" users.

Previously, I demoed hardcoded a default value for an Icon when both the name and image were not configured for an indicator, but I removed that when we set up that if everything is left blank then do not show an icon at all.  

However, this wouldn't work because there's a typo in the Icon Name.  And I don't think the SLDS Avatar notifies us if the icon doesn't exist, which means we'd have to track every valid option somewhere (CMDT or Custom Setting or CSV Static Resource) in order to validate it.

My concern is needing to manage the package with an upgrade every time SLDS adds a new icon.  Right now, [UnofficialSF is storing it as hardcoded list.](https://github.com/alexed1/LightningFlowComponents/blob/master/flow_screen_components/FlowScreenComponentsBasePack/force-app/main/default/lwc/fsc_pickIcon/fsc_pickIcon.js).  Ideally we'd retrieve this from a resource that can be managed by the user in a pinch, which is why I listed those 3 options above.

**Comment by nzgonjanin** [comment]
There is idea to try: 
If you use tag image and check url of icon you can set flag for icon display and do conditional display based on this flag.
This would be invisible image because of width and height size is set to 1. Purpose of it is to set flag. 


**HTML:**
<img src="https://your icon destination url/myicon.svg"  onload="{!c.pageOnline}" onerror="{!c.pageOffline}" width="1" height="1"/>

in controller you can define value for flag and then use it in HTML to display default icon.
controller methods

**Controller.js**
   pageOnline: function(component, event, helper) {
        component.set("v.urlValid",true);
    },
    pageOffline: function(component, event, helper) {
            component.set("v.urlValid",false);
    },

If I understand well issue details this may work. 
Let me know
